# Generated by Django 4.2 on 2024-03-20 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields

from pages.models import Page, Video, Tutorial

videos = []
tutorials = []


def sorter_data(apps, schema_editor):
    for page in Page.objects.all():
        if page.video:
            videos.append(Video(page=page, video_url=page.video))
        if page.content:
            tutorials.append((Tutorial(page=page, content=page.content)))

    Video.objects.bulk_create(videos)
    Tutorial.objects.bulk_create(tutorials)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('content', 'Content'), ('video', 'Video')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='pages.page')),
            ],
        ),
        migrations.RunPython(sorter_data)
    ]
