# Generated by Django 4.2 on 2024-03-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_change_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='video',
        ),
    ]
